version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend-api
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    container_name: redis-cache
    command:
      - "redis-server"
      - "--save"
      - ""
      - "--appendonly"
      - "no"
    restart: always
